# Generated by Django 5.2.5 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_create_issue_worklogs"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issueworklog",
            index=models.Index(fields=["issue", "log_date"], name="ext_worklogs_issue_log_date"),
        ),
    ]
