# Generated by Django 4.2.29 on 2026-04-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_issueworklog_issue_log_date_idx'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='issueworklog',
            managers=[
            ],
        ),
    ]
